nginx:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
node1:
    build: ./node
    links:
        - db
    ports:
        - "8888"
node2:
    build: ./node
    links:
        - db
    ports:
        - "8888"
node3:
    build: ./node
    links:
        - db
    ports:
        - "8888"
db:
    build: ./mongodb
    ports:
        - "27017"